---
# tasks file for rpi-install-kubeadm

- name: Rebooting in order to free resouces
  reboot:

- name: Configuring iptables bridge traffic 1/2
  lineinfile:
    path: /etc/modules-load.d/containerd.conf
    line: "net.bridge.bridge-nf-call-ip6tables = 1"
    state: present
    create: yes

- name: Configuring iptables bridge traffic 2/2
  lineinfile:
    path: /etc/modules-load.d/containerd.conf
    line: "net.bridge.bridge-nf-call-iptables = 1"
    state: present

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Add an Apt signing key, kubeadm
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add the repository needed to install kubeadm into sources list
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install kubelet
  apt:
    name: kubelet
    state: present

- name: Install kubeadm
  apt:
    name: kubeadm
    state: present

- name: Install kubectl
  apt:
    name: kubectl
    state: present

- name: Hold updates for kubelet, kubedm & kubectl
  shell:
    cmd: apt-mark hold kubelet kubeadm kubectl

- name: Allowing IP forward
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward=1'
    line: "net.ipv4.ip_forward=1"

# TODO: it's not necessary, but recommended
#       somehow it's not working in the ubuntu for raspberry pi 
#       needs additional investigation
#- name: Enabling huge pages
#  apt:
#    name: libhugetlbfs-bin
#    state: present

- name: Enable cgroup memory
  lineinfile:
      path: /boot/firmware/cmdline.txt
      regexp: '^(.*)\n'
      backrefs: yes
      line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'

- name: Reboot to start newly configured servicies
  reboot: